kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spire-server-external-cert-reader
  namespace: zero-trust-workload-identity-manager
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: spire
    app.kubernetes.io/managed-by: "zero-trust-workload-identity-manager"
    app.kubernetes.io/part-of: "zero-trust-workload-identity-manager"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: []  # Will be populated dynamically from externalSecretRef
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "watch"]

