apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
    service.beta.openshift.io/serving-cert-secret-name: webhook-server-certs
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: zero-trust-workload-identity-manager
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: zero-trust-workload-identity-manager
    name: zero-trust-workload-identity-manager
  name: zero-trust-workload-identity-manager-webhook-service
spec:
  ports:
  - name: webhook-server
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    name: zero-trust-workload-identity-manager
status:
  loadBalancer: {}
