resources:
- manifests.yaml
- service.yaml

patches:
- path: webhookcainjection_patch.yaml
  target:
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingWebhookConfiguration
    name: validating-webhook-configuration
