//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CASubject) DeepCopyInto(out *CASubject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CASubject.
func (in *CASubject) DeepCopy() *CASubject {
	if in == nil {
		return nil
	}
	out := new(CASubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonConfig) DeepCopyInto(out *CommonConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]*corev1.Toleration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1.Toleration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonConfig.
func (in *CommonConfig) DeepCopy() *CommonConfig {
	if in == nil {
		return nil
	}
	out := new(CommonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionalStatus) DeepCopyInto(out *ConditionalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionalStatus.
func (in *ConditionalStatus) DeepCopy() *ConditionalStatus {
	if in == nil {
		return nil
	}
	out := new(ConditionalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataStore) DeepCopyInto(out *DataStore) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataStore.
func (in *DataStore) DeepCopy() *DataStore {
	if in == nil {
		return nil
	}
	out := new(DataStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyManager) DeepCopyInto(out *KeyManager) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyManager.
func (in *KeyManager) DeepCopy() *KeyManager {
	if in == nil {
		return nil
	}
	out := new(KeyManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAttestor) DeepCopyInto(out *NodeAttestor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAttestor.
func (in *NodeAttestor) DeepCopy() *NodeAttestor {
	if in == nil {
		return nil
	}
	out := new(NodeAttestor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Persistence) DeepCopyInto(out *Persistence) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Persistence.
func (in *Persistence) DeepCopy() *Persistence {
	if in == nil {
		return nil
	}
	out := new(Persistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpiffeCSIDriverConfig) DeepCopyInto(out *SpiffeCSIDriverConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpiffeCSIDriverConfig.
func (in *SpiffeCSIDriverConfig) DeepCopy() *SpiffeCSIDriverConfig {
	if in == nil {
		return nil
	}
	out := new(SpiffeCSIDriverConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpiffeCSIDriverConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpiffeCSIDriverConfigList) DeepCopyInto(out *SpiffeCSIDriverConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpiffeCSIDriverConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpiffeCSIDriverConfigList.
func (in *SpiffeCSIDriverConfigList) DeepCopy() *SpiffeCSIDriverConfigList {
	if in == nil {
		return nil
	}
	out := new(SpiffeCSIDriverConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpiffeCSIDriverConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpiffeCSIDriverConfigSpec) DeepCopyInto(out *SpiffeCSIDriverConfigSpec) {
	*out = *in
	in.CommonConfig.DeepCopyInto(&out.CommonConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpiffeCSIDriverConfigSpec.
func (in *SpiffeCSIDriverConfigSpec) DeepCopy() *SpiffeCSIDriverConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SpiffeCSIDriverConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpiffeCSIDriverConfigStatus) DeepCopyInto(out *SpiffeCSIDriverConfigStatus) {
	*out = *in
	in.ConditionalStatus.DeepCopyInto(&out.ConditionalStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpiffeCSIDriverConfigStatus.
func (in *SpiffeCSIDriverConfigStatus) DeepCopy() *SpiffeCSIDriverConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SpiffeCSIDriverConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireAgentConfig) DeepCopyInto(out *SpireAgentConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireAgentConfig.
func (in *SpireAgentConfig) DeepCopy() *SpireAgentConfig {
	if in == nil {
		return nil
	}
	out := new(SpireAgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpireAgentConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireAgentConfigList) DeepCopyInto(out *SpireAgentConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpireAgentConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireAgentConfigList.
func (in *SpireAgentConfigList) DeepCopy() *SpireAgentConfigList {
	if in == nil {
		return nil
	}
	out := new(SpireAgentConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpireAgentConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireAgentConfigSpec) DeepCopyInto(out *SpireAgentConfigSpec) {
	*out = *in
	if in.NodeAttestor != nil {
		in, out := &in.NodeAttestor, &out.NodeAttestor
		*out = new(NodeAttestor)
		**out = **in
	}
	if in.WorkloadAttestors != nil {
		in, out := &in.WorkloadAttestors, &out.WorkloadAttestors
		*out = new(WorkloadAttestors)
		(*in).DeepCopyInto(*out)
	}
	in.CommonConfig.DeepCopyInto(&out.CommonConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireAgentConfigSpec.
func (in *SpireAgentConfigSpec) DeepCopy() *SpireAgentConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SpireAgentConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireAgentConfigStatus) DeepCopyInto(out *SpireAgentConfigStatus) {
	*out = *in
	in.ConditionalStatus.DeepCopyInto(&out.ConditionalStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireAgentConfigStatus.
func (in *SpireAgentConfigStatus) DeepCopy() *SpireAgentConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SpireAgentConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireOIDCDiscoveryProviderConfig) DeepCopyInto(out *SpireOIDCDiscoveryProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireOIDCDiscoveryProviderConfig.
func (in *SpireOIDCDiscoveryProviderConfig) DeepCopy() *SpireOIDCDiscoveryProviderConfig {
	if in == nil {
		return nil
	}
	out := new(SpireOIDCDiscoveryProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpireOIDCDiscoveryProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireOIDCDiscoveryProviderConfigList) DeepCopyInto(out *SpireOIDCDiscoveryProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpireOIDCDiscoveryProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireOIDCDiscoveryProviderConfigList.
func (in *SpireOIDCDiscoveryProviderConfigList) DeepCopy() *SpireOIDCDiscoveryProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(SpireOIDCDiscoveryProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpireOIDCDiscoveryProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireOIDCDiscoveryProviderConfigSpec) DeepCopyInto(out *SpireOIDCDiscoveryProviderConfigSpec) {
	*out = *in
	in.CommonConfig.DeepCopyInto(&out.CommonConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireOIDCDiscoveryProviderConfigSpec.
func (in *SpireOIDCDiscoveryProviderConfigSpec) DeepCopy() *SpireOIDCDiscoveryProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SpireOIDCDiscoveryProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireOIDCDiscoveryProviderConfigStatus) DeepCopyInto(out *SpireOIDCDiscoveryProviderConfigStatus) {
	*out = *in
	in.ConditionalStatus.DeepCopyInto(&out.ConditionalStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireOIDCDiscoveryProviderConfigStatus.
func (in *SpireOIDCDiscoveryProviderConfigStatus) DeepCopy() *SpireOIDCDiscoveryProviderConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SpireOIDCDiscoveryProviderConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireServer) DeepCopyInto(out *SpireServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireServer.
func (in *SpireServer) DeepCopy() *SpireServer {
	if in == nil {
		return nil
	}
	out := new(SpireServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpireServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireServerList) DeepCopyInto(out *SpireServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpireServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireServerList.
func (in *SpireServerList) DeepCopy() *SpireServerList {
	if in == nil {
		return nil
	}
	out := new(SpireServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpireServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireServerSpec) DeepCopyInto(out *SpireServerSpec) {
	*out = *in
	if in.KeyManager != nil {
		in, out := &in.KeyManager, &out.KeyManager
		*out = new(KeyManager)
		**out = **in
	}
	if in.CASubject != nil {
		in, out := &in.CASubject, &out.CASubject
		*out = new(CASubject)
		**out = **in
	}
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(Persistence)
		**out = **in
	}
	if in.Datastore != nil {
		in, out := &in.Datastore, &out.Datastore
		*out = new(DataStore)
		(*in).DeepCopyInto(*out)
	}
	in.CommonConfig.DeepCopyInto(&out.CommonConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireServerSpec.
func (in *SpireServerSpec) DeepCopy() *SpireServerSpec {
	if in == nil {
		return nil
	}
	out := new(SpireServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpireServerStatus) DeepCopyInto(out *SpireServerStatus) {
	*out = *in
	in.ConditionalStatus.DeepCopyInto(&out.ConditionalStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpireServerStatus.
func (in *SpireServerStatus) DeepCopy() *SpireServerStatus {
	if in == nil {
		return nil
	}
	out := new(SpireServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadAttestors) DeepCopyInto(out *WorkloadAttestors) {
	*out = *in
	if in.WorkloadAttestorsVerification != nil {
		in, out := &in.WorkloadAttestorsVerification, &out.WorkloadAttestorsVerification
		*out = new(WorkloadAttestorsVerification)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadAttestors.
func (in *WorkloadAttestors) DeepCopy() *WorkloadAttestors {
	if in == nil {
		return nil
	}
	out := new(WorkloadAttestors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadAttestorsVerification) DeepCopyInto(out *WorkloadAttestorsVerification) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadAttestorsVerification.
func (in *WorkloadAttestorsVerification) DeepCopy() *WorkloadAttestorsVerification {
	if in == nil {
		return nil
	}
	out := new(WorkloadAttestorsVerification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustWorkloadIdentityManager) DeepCopyInto(out *ZeroTrustWorkloadIdentityManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustWorkloadIdentityManager.
func (in *ZeroTrustWorkloadIdentityManager) DeepCopy() *ZeroTrustWorkloadIdentityManager {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustWorkloadIdentityManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZeroTrustWorkloadIdentityManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustWorkloadIdentityManagerList) DeepCopyInto(out *ZeroTrustWorkloadIdentityManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ZeroTrustWorkloadIdentityManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustWorkloadIdentityManagerList.
func (in *ZeroTrustWorkloadIdentityManagerList) DeepCopy() *ZeroTrustWorkloadIdentityManagerList {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustWorkloadIdentityManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZeroTrustWorkloadIdentityManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustWorkloadIdentityManagerSpec) DeepCopyInto(out *ZeroTrustWorkloadIdentityManagerSpec) {
	*out = *in
	in.CommonConfig.DeepCopyInto(&out.CommonConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustWorkloadIdentityManagerSpec.
func (in *ZeroTrustWorkloadIdentityManagerSpec) DeepCopy() *ZeroTrustWorkloadIdentityManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustWorkloadIdentityManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroTrustWorkloadIdentityManagerStatus) DeepCopyInto(out *ZeroTrustWorkloadIdentityManagerStatus) {
	*out = *in
	in.ConditionalStatus.DeepCopyInto(&out.ConditionalStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroTrustWorkloadIdentityManagerStatus.
func (in *ZeroTrustWorkloadIdentityManagerStatus) DeepCopy() *ZeroTrustWorkloadIdentityManagerStatus {
	if in == nil {
		return nil
	}
	out := new(ZeroTrustWorkloadIdentityManagerStatus)
	in.DeepCopyInto(out)
	return out
}
